package com.oujiong.mapper;


import com.oujiong.entity.Log;
import com.oujiong.entity.User;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface LogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbg.generated Mon Nov 07 10:03:08 UTC 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbg.generated Mon Nov 07 10:03:08 UTC 2022
     */
    int insert(Log record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbg.generated Mon Nov 07 10:03:08 UTC 2022
     */
    int insertSelective(Log record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbg.generated Mon Nov 07 10:03:08 UTC 2022
     */
    Log selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbg.generated Mon Nov 07 10:03:08 UTC 2022
     */
    int updateByPrimaryKeySelective(Log record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbg.generated Mon Nov 07 10:03:08 UTC 2022
     */
    int updateByPrimaryKey(Log record);

    List<Log> selectAll();

    void insertBatch(List<Log> lists);

    List<Log> query(Log log);
}